name: Scorecard Security Check

on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master']
  schedule:
    - cron: '0 0 * * 1' # Weekly on Mondays at 00:00

jobs:
  scorecard:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    name: Scorecard Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e # v5.0.0

      - name: Run Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_format: sarif
          results_file: ./scorecard-results.sarif
          publish_results: false # API Scorecard
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@cf1bb45a277cb3c205638b2cd5c984db1c46a412 # v4.31.7
        with:
          sarif_file: ./scorecard-results.sarif
